"""Add gender to User model

Revision ID: f4630ad02157
Revises: 49e5b3341409
Create Date: 2025-09-13 23:03:44.885359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4630ad02157'
down_revision = '49e5b3341409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender_enum', native_enum=False), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
